### ISSUE TITLE
HIV reference genome

### ISSUE THREAD

**Issue by emanuellegrody** [galelab/scViralQuant#1]
Hello there, would you please share the HIV reference (.fasta and .gtf) that are used for the preprint? Specifically, I'm wondering how you resolved the issue of reads aligning to multiple overlapping genes.
Thank you! I am looking forward to trying this tool.

**Comment by lwhitmore** [comment]
Hi, 
Here is a path to the genomes I used in the preprint specifically the HIV one. https://github.com/galelab/Whitmore_scViralQuant_testSets/tree/main/Bradley_et_al_testSet/genomefiles

Basically the tool does two alignments. One treating the whole genome as one gene and a second one if a gtf is provided quantifying the reads aligning to specific genes.  Let me know if you have more questions!
Leanne
