### ISSUE TITLE
custom reference with the viral sequence added to human reference

### ISSUE THREAD

**Issue by sm2695** [galelab/scViralQuant#5]
Hi, 

Thank you for developing a great tool! Does the tool only take unaligned reads from cellranger's output? 

I ran `cellranger count` on my files with a custom reference containing the human reference genome and the viral genome added to it as a single exon. This also results in viral transcripts being 'aligned' to this reference. Does it make sense to run scpathoquant on such output files? 

Thanks in advance!

**Comment by lwhitmore** [comment]
Hi, 
It does not make sense to run scPathoQuant on that output if the viral genome has already been added to the human reference genome.  scPathoQuant would not find any viral reads as they have already been aligned in the first analysis. 
Thanks for your question and let me know if you have others!

**Comment by sm2695** [comment]
Thanks for your response!
